# Generated by Django 4.2.23 on 2025-07-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseguide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='contact_info',
            field=models.TextField(blank=True),
        ),
    ]
