# Generated by Django 4.2.23 on 2025-07-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseguide', '0002_course_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='contact_info',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
