# Generated by Django 4.2.23 on 2025-07-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseguide', '0003_alter_course_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
