# Generated by Django 4.2.23 on 2025-07-30 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courseguide', '0004_course_updated_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoleGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.IntegerField(choices=[(1, 'Hole 1'), (2, 'Hole 2'), (3, 'Hole 3'), (4, 'Hole 4'), (5, 'Hole 5'), (6, 'Hole 6'), (7, 'Hole 7'), (8, 'Hole 8'), (9, 'Hole 9'), (10, 'Hole 10'), (11, 'Hole 11'), (12, 'Hole 12'), (13, 'Hole 13'), (14, 'Hole 14'), (15, 'Hole 15'), (16, 'Hole 16'), (17, 'Hole 17'), (18, 'Hole 18')])),
                ('name', models.CharField(blank=True, max_length=100)),
                ('par', models.PositiveSmallIntegerField()),
                ('yardage', models.PositiveIntegerField()),
                ('guide', models.TextField(help_text='Strategic tips or description for playing the hole.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hole_images/')),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hole_guides', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holes', to='courseguide.course')),
            ],
            options={
                'ordering': ['hole_number'],
                'unique_together': {('course', 'hole_number')},
            },
        ),
    ]
