# Generated by Django 4.2.23 on 2025-07-30 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseguide', '0005_holeguide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holeguide',
            name='image',
        ),
    ]
