# Generated by Django 4.2.23 on 2025-07-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseguide', '0006_remove_holeguide_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='holeguide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hole_images/'),
        ),
    ]
