# Generated by Django 4.2.23 on 2025-07-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseguide', '0007_holeguide_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='holeguide',
            name='stroke_index',
            field=models.PositiveSmallIntegerField(default=6, help_text='1 = hardest hole, 18 = easiest'),
            preserve_default=False,
        ),
    ]
