# Generated by Django 4.2.22 on 2025-08-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseguide', '0009_alter_course_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holeguide',
            name='hole_number',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18')]),
        ),
    ]
