# Generated by Django 4.2.22 on 2025-08-02 23:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseguide', '0010_alter_holeguide_hole_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
