# Generated by Django 4.2.22 on 2025-08-03 18:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseguide', '0011_course_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holeguide',
            name='image',
        ),
        migrations.AddField(
            model_name='holeguide',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
